bundle:
    class: '\Akuma\Bundle\TestBundle\AkumaTestBundle'
    priority: -1
    kernel: true
    environments: ['test', 'prod', 'dev']
    require:
        - {class: 'AppBundle\AppBundle', kernel: true}
        - {class: 'AppBundle\AppBundle', kernel: true}
        - {class: 'AppBundle\AppBundle', kernel: true}
        - {class: 'AppBundle\AppBundle', kernel: true}
        - {class: 'AppBundle\AppBundle', kernel: true}
        - {class: 'AppBundle\AppBundle', kernel: true}
        - {class: 'AppBundle\AppBundle', kernel: true}
